### ISSUE TITLE
Open-Source License

### ISSUE THREAD

**Issue by Umofomia** [jhsu/google-qr#7]
Being that this repository is publicly available on GitHub, it is ostensibly open source, but I don't see any licensing terms that is typical of open-source projects. The lack of an explicit licensing statement may make it hard for others to legally make use of this project.

Check out https://help.github.com/articles/open-source-licensing for more information and how to easily choose and add a license for this project. Please consider adding one so that others will be able to unambiguously use and contribute to this project.

Thanks!

**Comment by Umofomia** [comment]
@jhsu Thanks for quickly getting on this; I really appreciate it!

**Comment by jhsu** [comment]
no problem!
