### ISSUE TITLE
Google Infographics was turned off

### ISSUE THREAD

**Issue by tnandate** [jhsu/google-qr#8]
This Gem is dependent on Google Infographics, but Google Infographics was turned off on March 18, 2019.
https://developers.google.com/chart/infographics/

**Comment by jhsu** [comment]
yep, I recommend looking at an alternative library that can actually generate qr codes https://www.ruby-toolbox.com/categories/QR_Codes

**Comment by tnandate** [comment]
All right. Thank you for your answer!
